#**Imprting Libraries and datasets**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/gld_price_data.csv')
df

Date          SPX         GLD        USO      SLV   EUR/USD
0      1/2/2008  1447.160034   84.860001  78.470001  15.1800  1.471692
1      1/3/2008  1447.160034   85.570000  78.370003  15.2850  1.474491
2      1/4/2008  1411.630005   85.129997  77.309998  15.1670  1.475492
3      1/7/2008  1416.180054   84.769997  75.500000  15.0530  1.468299
4      1/8/2008  1390.189941   86.779999  76.059998  15.5900  1.557099
...         ...          ...         ...        ...      ...       ...
2285   5/8/2018  2671.919922  124.589996  14.060000  15.5100  1.186789
2286   5/9/2018  2697.790039  124.330002  14.370000  15.5300  1.184722
2287  5/10/2018  2723.070068  125.180000  14.410000  15.7400  1.191753
2288  5/14/2018  2730.129883  124.489998  14.380000  15.5600  1.193118
2289  5/16/2018  2725.780029  122.543800  14.405800  15.4542  1.182033

[2290 rows x 6 columns]

# **Data Preprocessing**

In [ ]:
df=df.drop(['Date'],axis=1)
df

SPX         GLD        USO      SLV   EUR/USD
0     1447.160034   84.860001  78.470001  15.1800  1.471692
1     1447.160034   85.570000  78.370003  15.2850  1.474491
2     1411.630005   85.129997  77.309998  15.1670  1.475492
3     1416.180054   84.769997  75.500000  15.0530  1.468299
4     1390.189941   86.779999  76.059998  15.5900  1.557099
...           ...         ...        ...      ...       ...
2285  2671.919922  124.589996  14.060000  15.5100  1.186789
2286  2697.790039  124.330002  14.370000  15.5300  1.184722
2287  2723.070068  125.180000  14.410000  15.7400  1.191753
2288  2730.129883  124.489998  14.380000  15.5600  1.193118
2289  2725.780029  122.543800  14.405800  15.4542  1.182033

[2290 rows x 5 columns]

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
print(x)

[[1447.160034   84.860001   78.470001   15.18    ]
 [1447.160034   85.57       78.370003   15.285   ]
 [1411.630005   85.129997   77.309998   15.167   ]
 ...
 [2723.070068  125.18       14.41       15.74    ]
 [2730.129883  124.489998   14.38       15.56    ]
 [2725.780029  122.5438     14.4058     15.4542  ]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#**Linear Regression**

In [ ]:
from sklearn.linear_model import LinearRegression
lr1=LinearRegression()
lr1

LinearRegression()

In [ ]:
lr1.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred1=lr1.predict(x_test)
y_pred1

array([1.15065114, 1.12331969, 1.36991108, 1.36916383, 1.32122956,
       1.32091583, 1.30596109, 1.1851247 , 1.2313907 , 1.32906865,
       1.36734302, 1.16540031, 1.31747238, 1.14394866, 1.18723307,
       1.23499999, 1.33076635, 1.14904689, 1.32168838, 1.17702196,
       1.12420195, 1.1838077 , 1.41514726, 1.15258036, 1.37320454,
       1.36532929, 1.22904756, 1.35897943, 1.29903444, 1.15167716,
       1.19268382, 1.52770803, 1.1517045 , 1.34057924, 1.35903557,
       1.27945354, 1.29199409, 1.55570229, 1.50638781, 1.11742947,
       1.16580278, 1.35328006, 1.24439082, 1.28933641, 1.4459538 ,
       1.35994001, 1.14679415, 1.32718572, 1.34742431, 1.34684897,
       1.35187434, 1.19191552, 1.32835473, 1.18336354, 1.3564125 ,
       1.32988616, 1.36486854, 1.12732099, 1.33366571, 1.21068542,
       1.12210661, 1.39067559, 1.26974826, 1.31682229, 1.27911945,
       1.34844381, 1.47444523, 1.11851279, 1.34850291, 1.17766462,
       1.15212541, 1.29311773, 1.38501208, 1.1847674 , 1.12507

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred1)

0.7451516859061864

# **RandomForestRegressor**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor2=RandomForestRegressor(random_state=0,n_estimators=100)
regressor2

RandomForestRegressor(random_state=0)

In [ ]:
regressor2.fit(x_train,y_train)

RandomForestRegressor(random_state=0)

In [ ]:
y_pred2=regressor2.predict(x_test)
y_pred2

array([1.05839166, 1.17061102, 1.42630343, 1.35763265, 1.27596163,
       1.32890996, 1.35296355, 1.11467424, 1.24998553, 1.30579072,
       1.32666874, 1.07630168, 1.26915212, 1.09525057, 1.09468427,
       1.24526156, 1.32858802, 1.11257307, 1.23937621, 1.12095999,
       1.1652681 , 1.16443525, 1.41264426, 1.12824919, 1.32640391,
       1.25898616, 1.2497754 , 1.33881441, 1.32749172, 1.11473013,
       1.12031799, 1.43864696, 1.10206459, 1.38316709, 1.31612804,
       1.33759647, 1.36228951, 1.55243314, 1.40734382, 1.20322032,
       1.07643042, 1.31435369, 1.26331901, 1.36183843, 1.43330532,
       1.35529387, 1.10869406, 1.31113061, 1.43348376, 1.4948162 ,
       1.35822665, 1.11199697, 1.29218069, 1.12262391, 1.30935724,
       1.41637741, 1.32334872, 1.1360969 , 1.29128263, 1.24017417,
       1.23066704, 1.27317943, 1.29344786, 1.33549384, 1.35911288,
       1.36553323, 1.47697596, 1.21638703, 1.49103718, 1.12214438,
       1.12238604, 1.26400689, 1.43209209, 1.12569074, 1.16837

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred2)

0.9780343093596998

#**SVM**

In [ ]:
from sklearn.svm import SVR
regressor3=SVR(kernel='rbf')
regressor3

SVR()

In [ ]:
regressor3.fit(x_train,y_train)

SVR()

In [ ]:
y_pred3=regressor3.predict(x_test)
y_pred3

array([1.14465089, 1.11879505, 1.36653137, 1.36997743, 1.36325413,
       1.30181714, 1.32761588, 1.17634254, 1.20392157, 1.37272565,
       1.36389146, 1.18116289, 1.36012174, 1.19038645, 1.17807652,
       1.2128332 , 1.37756593, 1.2059957 , 1.35527668, 1.22125858,
       1.12580152, 1.19421688, 1.37961787, 1.16713866, 1.37375554,
       1.33856865, 1.20742307, 1.35844062, 1.32164406, 1.1479702 ,
       1.17973919, 1.47675532, 1.15535459, 1.37991925, 1.36049471,
       1.25248172, 1.24721134, 1.47037224, 1.47123678, 1.15305075,
       1.17630475, 1.33054642, 1.22721874, 1.24781048, 1.37879307,
       1.35598726, 1.20676818, 1.370977  , 1.37176009, 1.3727781 ,
       1.36978233, 1.17418334, 1.34516923, 1.17519993, 1.36089194,
       1.37046018, 1.37320714, 1.11835727, 1.34600127, 1.19767092,
       1.13905798, 1.37920466, 1.23307992, 1.3051749 , 1.27418387,
       1.37270437, 1.44577575, 1.14068443, 1.37664856, 1.21099316,
       1.22598782, 1.29473938, 1.37052896, 1.19935973, 1.12680

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7451516859061864